package frontEnd;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.Timer;
import util.Location;
import backEnd.Turtle;


/**
 * TurtleView class extends JComponent. Receives information from Canvas in the form of a Turtle
 * Object. Draws Turtle and lines generated by Turtle movement.
 * 
 * @author Danny Goodman
 */
public class TurtleView extends JComponent {

    private static final int DEFAULT_HEADING = 90;
    private static final Location DEFAULT_LOCATION = new Location(0, 0);
    private static final long serialVersionUID = 1L;
    private static final int VIEW_HEIGHT = 495;
    private static final int VIEW_WIDTH = 620;
    public static final int FRAMES_PER_SECOND = 1000;
    public static final int ONE_SECOND = 1000;
    public static final int DEFAULT_DELAY = ONE_SECOND / FRAMES_PER_SECOND;

    private Location myTurtleLocation;
    private Location myTurtleNextLocation;
    private double myTurtleHeading;
    private boolean myTurtlePenDown;
    private boolean myTurtleVisible;
    private TurtleDrawer myTurtleDrawer;
    private List<Turtle> myChangesQueue;
    private Timer myTimer;

    /**
     * TurtleView Constructor. Sets size. Initializes turtle parameters. Creates a Timer to paint
     * the turtle at each timer event.
     */
    public TurtleView () {
        setPreferredSize(new Dimension(VIEW_WIDTH, VIEW_HEIGHT));
        setFocusable(true);
        requestFocus();
        resetTurtle();
        myTurtleDrawer = new DefaultTurtleDrawer(this);
        myTimer = new Timer(DEFAULT_DELAY, new ActionListener() {
            public void actionPerformed (ActionEvent e) {
                checkQueue();
            }
        });
        myTimer.start();
    }

    /**
     * Paint the contents of the canvas.
     * 
     * Never called by you directly, instead called by Java runtime
     * when area of screen covered by this container needs to be
     * displayed (i.e., creation, uncovering, change in status)
     * 
     * @param pen - used to paint shape on the screen
     */
    @Override
    public void paintComponent (Graphics pen) {
        pen.setColor(Color.WHITE);
        pen.fillRect(0, 0, getSize().width, getSize().height);
        drawTurtle(pen);
    }

    /**
     * Adds a Turtle object to the queue to be updated from later.
     * 
     * @param changedTurtle - Turtle object containing changes in instance variables
     */
    public void addToQueue (Turtle changedTurtle) {
        myChangesQueue.add(changedTurtle);
    }

    /**
     * Updates turtle based on next turtle in the queue. Called by the timer.
     */
    public void checkQueue () {
        if (!myChangesQueue.isEmpty()) {
            updateTurtle(myChangesQueue.remove(0));
        }
    }

    /**
     * Updates the Turtle parameters based on the new Turtle information. Calls repaint().
     * 
     * @param changedTurtle - contains changes in instance variables
     */
    public void updateTurtle (Turtle changedTurtle) {
        myTurtleNextLocation = changedTurtle.getLocation();
        myTurtleHeading = changedTurtle.getHeading();
        myTurtlePenDown = changedTurtle.isPenDown();
        myTurtleVisible = changedTurtle.isVisible();
        repaint();
    }

    /**
     * Clears the trails from the List so that they are no longer painted.
     */
    public void clearTrails () {
        myTurtleDrawer.clearTrail();
        repaint();
    }

    private void drawTurtle (Graphics pen) {
        if (myTurtlePenDown) {
            myTurtleDrawer.addTrail(myTurtleLocation, myTurtleNextLocation);
        }
        myTurtleDrawer.drawTrail(pen);
        if (myTurtleVisible) {
            myTurtleDrawer.drawBody(pen, myTurtleLocation, myTurtleNextLocation, myTurtleHeading);
        }
        myTurtleLocation = new Location(myTurtleNextLocation);
    }

    private void resetTurtle () {
        myTurtleLocation = DEFAULT_LOCATION;
        myTurtleNextLocation = DEFAULT_LOCATION;
        myTurtleHeading = DEFAULT_HEADING;
        myTurtlePenDown = true;
        myTurtleVisible = true;
        myChangesQueue = new ArrayList<Turtle>();
    }

    public Location translateCoordinates(Location point){
            double centerX = getBounds().getWidth() / 2;
            double centerY = getBounds().getHeight() / 2;
            return new Location(centerX + point.getX(), centerY - point.getY());
    }
}
